apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ops-config
  namespace: kubernetes-operations-dashboard
data:
  APP_MODE: "prod"
  DEV_MODE: "false"
  AUTH_ENABLED: "true"
  AUTH_ALLOW_HEADER_TOKEN: "false"
  WRITE_ACTIONS_ENABLED: "false"
  DATABASE_DRIVER: "postgres"
  DATABASE_MIGRATIONS_AUTO: "true"
  MEMORY_STORE: "sql"
  AUDIT_STORE: "sql"
  RATE_LIMIT_REQUESTS: "180"
