import {
  AlarmClock,
  Archive,
  BookOpen,
  Bot,
  BrainCircuit,
  Boxes,
  Briefcase,
  ClipboardList,
  Clock3,
  Copy,
  Cpu,
  Database,
  FolderTree,
  Globe,
  Gauge,
  Goal,
  HardDrive,
  KeyRound,
  Layers,
  LayoutDashboard,
  LineChart,
  Network,
  Rocket,
  ScanSearch,
  ScrollText,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  SlidersHorizontal,
  TrendingUp,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { View } from "../types";

export const VIEW_ICON: Record<View, LucideIcon> = {
  overview: LayoutDashboard,
  pods: Boxes,
  deployments: Rocket,
  replicasets: Copy,
  statefulsets: Database,
  daemonsets: Server,
  jobs: Briefcase,
  cronjobs: Clock3,
  services: Network,
  ingresses: Globe,
  networkpolicies: Shield,
  configmaps: SlidersHorizontal,
  secrets: KeyRound,
  persistentvolumes: HardDrive,
  persistentvolumeclaims: Archive,
  storageclasses: Layers,
  nodes: Cpu,
  namespaces: FolderTree,
  events: Zap,
  serviceaccounts: Users,
  rbac: ShieldCheck,
  metrics: LineChart,
  slo: Goal,
  rightsizing: Gauge,
  audit: ScrollText,
  predictions: TrendingUp,
  diagnostics: ScanSearch,
  ghost: Network,
  shiftbrief: AlarmClock,
  playbooks: BookOpen,
  incidents: Siren,
  remediation: Wrench,
  memory: BrainCircuit,
  riskguard: ShieldAlert,
  postmortems: ClipboardList,
  assistant: Bot,
};
