apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-operations-dashboard
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - predictor-deployment.yaml
  - predictor-service.yaml
  - ghost-engine-deployment.yaml
  - ghost-engine-service.yaml
  - jaeger-deployment.yaml
  - jaeger-service.yaml
  - pdb.yaml
  - hpa.yaml
  - networkpolicy.yaml
