package db

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS incidents (
		id TEXT PRIMARY KEY,
		title TEXT NOT NULL,
		severity TEXT NOT NULL,
		status TEXT NOT NULL,
		summary TEXT NOT NULL,
		opened_at TEXT NOT NULL,
		resolved_at TEXT NOT NULL,
		timeline_json TEXT NOT NULL,
		runbook_json TEXT NOT NULL,
		affected_resources_json TEXT NOT NULL,
		associated_remediation_ids_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_incidents_opened_at ON incidents(opened_at DESC)`,
	`CREATE TABLE IF NOT EXISTS remediation_proposals (
		id TEXT PRIMARY KEY,
		kind TEXT NOT NULL,
		status TEXT NOT NULL,
		incident_id TEXT NOT NULL,
		resource TEXT NOT NULL,
		namespace TEXT NOT NULL,
		reason TEXT NOT NULL,
		risk_level TEXT NOT NULL,
		dry_run_result TEXT NOT NULL,
		execution_result TEXT NOT NULL,
		approved_by TEXT NOT NULL,
		approved_at TEXT NOT NULL,
		rejected_by TEXT NOT NULL,
		rejected_at TEXT NOT NULL,
		rejected_reason TEXT NOT NULL,
		executed_by TEXT NOT NULL,
		executed_at TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_remediation_status ON remediation_proposals(status)`,
	`CREATE INDEX IF NOT EXISTS idx_remediation_created_at ON remediation_proposals(created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS postmortems (
		id TEXT PRIMARY KEY,
		incident_id TEXT NOT NULL,
		incident_title TEXT NOT NULL,
		severity TEXT NOT NULL,
		opened_at TEXT NOT NULL,
		resolved_at TEXT NOT NULL,
		duration TEXT NOT NULL,
		generated_at TEXT NOT NULL,
		method TEXT NOT NULL,
		root_cause TEXT NOT NULL,
		impact TEXT NOT NULL,
		prevention TEXT NOT NULL,
		timeline_markdown TEXT NOT NULL,
		runbook_markdown TEXT NOT NULL,
		timeline_json TEXT NOT NULL,
		runbook_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_postmortems_incident_id ON postmortems(incident_id)`,
	`CREATE INDEX IF NOT EXISTS idx_postmortems_generated_at ON postmortems(generated_at DESC)`,
	`CREATE TABLE IF NOT EXISTS alert_lifecycle (
		alert_id TEXT PRIMARY KEY,
		node TEXT NOT NULL,
		rule TEXT NOT NULL,
		status TEXT NOT NULL,
		note TEXT NOT NULL,
		snoozed_until TEXT NOT NULL,
		updated_by TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_alert_lifecycle_updated_at ON alert_lifecycle(updated_at DESC)`,
}
