package db

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS incidents (
		id TEXT PRIMARY KEY,
		title TEXT NOT NULL,
		severity TEXT NOT NULL,
		status TEXT NOT NULL,
		summary TEXT NOT NULL,
		opened_at TEXT NOT NULL,
		resolved_at TEXT NOT NULL,
		timeline_json TEXT NOT NULL,
		runbook_json TEXT NOT NULL,
		affected_resources_json TEXT NOT NULL,
		associated_remediation_ids_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_incidents_opened_at ON incidents(opened_at DESC)`,
	`CREATE TABLE IF NOT EXISTS remediation_proposals (
		id TEXT PRIMARY KEY,
		kind TEXT NOT NULL,
		status TEXT NOT NULL,
		incident_id TEXT NOT NULL,
		resource TEXT NOT NULL,
		namespace TEXT NOT NULL,
		reason TEXT NOT NULL,
		risk_level TEXT NOT NULL,
		dry_run_result TEXT NOT NULL,
		execution_result TEXT NOT NULL,
		approved_by TEXT NOT NULL,
		approved_at TEXT NOT NULL,
		rejected_by TEXT NOT NULL,
		rejected_at TEXT NOT NULL,
		rejected_reason TEXT NOT NULL,
		executed_by TEXT NOT NULL,
		executed_at TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_remediation_status ON remediation_proposals(status)`,
	`CREATE INDEX IF NOT EXISTS idx_remediation_created_at ON remediation_proposals(created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS remediation_gitops_artifacts (
		proposal_id TEXT PRIMARY KEY REFERENCES remediation_proposals(id) ON DELETE CASCADE,
		support_level TEXT NOT NULL,
		strategy TEXT NOT NULL,
		summary TEXT NOT NULL,
		branch_name TEXT NOT NULL,
		pr_title TEXT NOT NULL,
		commit_message TEXT NOT NULL,
		target_path TEXT NOT NULL,
		target_kind TEXT NOT NULL,
		target_namespace TEXT NOT NULL,
		target_name TEXT NOT NULL,
		format TEXT NOT NULL,
		artifact_body TEXT NOT NULL,
		instructions_json TEXT NOT NULL,
		generated_by TEXT NOT NULL,
		generated_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS postmortems (
		id TEXT PRIMARY KEY,
		incident_id TEXT NOT NULL,
		incident_title TEXT NOT NULL,
		severity TEXT NOT NULL,
		opened_at TEXT NOT NULL,
		resolved_at TEXT NOT NULL,
		duration TEXT NOT NULL,
		generated_at TEXT NOT NULL,
		method TEXT NOT NULL,
		root_cause TEXT NOT NULL,
		impact TEXT NOT NULL,
		prevention TEXT NOT NULL,
		timeline_markdown TEXT NOT NULL,
		runbook_markdown TEXT NOT NULL,
		timeline_json TEXT NOT NULL,
		runbook_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_postmortems_incident_id ON postmortems(incident_id)`,
	`CREATE INDEX IF NOT EXISTS idx_postmortems_generated_at ON postmortems(generated_at DESC)`,
	`CREATE TABLE IF NOT EXISTS alert_lifecycle (
		alert_id TEXT PRIMARY KEY,
		node TEXT NOT NULL,
		rule TEXT NOT NULL,
		status TEXT NOT NULL,
		note TEXT NOT NULL,
		snoozed_until TEXT NOT NULL,
		updated_by TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_alert_lifecycle_updated_at ON alert_lifecycle(updated_at DESC)`,
	`CREATE TABLE IF NOT EXISTS ghost_simulations (
		id TEXT PRIMARY KEY,
		created_at TEXT NOT NULL,
		action TEXT NOT NULL,
		node_name TEXT NOT NULL,
		topology_hash TEXT NOT NULL,
		request_json TEXT NOT NULL,
		result_json TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_ghost_simulations_created_at ON ghost_simulations(created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS node_telemetry_samples (
		id TEXT PRIMARY KEY,
		agent_id TEXT NOT NULL,
		source TEXT NOT NULL,
		captured_at TEXT NOT NULL,
		received_at TEXT NOT NULL,
		nodes_json TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_node_telemetry_received_at ON node_telemetry_samples(received_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_node_telemetry_agent_id ON node_telemetry_samples(agent_id)`,
	`CREATE TABLE IF NOT EXISTS memory_runbooks (
		id TEXT PRIMARY KEY,
		title TEXT NOT NULL,
		tags_json TEXT NOT NULL,
		description TEXT NOT NULL,
		steps_json TEXT NOT NULL,
		embedding_json TEXT NOT NULL,
		usage_count INTEGER NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_memory_runbooks_updated_at ON memory_runbooks(updated_at DESC)`,
	`CREATE TABLE IF NOT EXISTS memory_fix_patterns (
		id TEXT PRIMARY KEY,
		incident_id TEXT NOT NULL,
		proposal_id TEXT NOT NULL,
		title TEXT NOT NULL,
		description TEXT NOT NULL,
		resource TEXT NOT NULL,
		kind TEXT NOT NULL,
		recorded_by TEXT NOT NULL,
		recorded_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_memory_fix_patterns_recorded_at ON memory_fix_patterns(recorded_at DESC)`,
	`CREATE TABLE IF NOT EXISTS audit_entries (
		id TEXT PRIMARY KEY,
		sequence_id INTEGER NOT NULL,
		timestamp TEXT NOT NULL,
		action TEXT NOT NULL,
		status INTEGER NOT NULL,
		success BOOLEAN NOT NULL,
		hash TEXT NOT NULL,
		signature TEXT NOT NULL,
		entry_json TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_entries_sequence_id ON audit_entries(sequence_id DESC)`,
}
